const name = 'Adhithi'
const count = 5

//console.log(name + count) old syntax
console.log(`Hello my name is ${name} and count is ${count}`) // ` ` is called backtick

const name1 = new String('Adhithi') // another way of declaring string
console.log(name1[0])
console.log(name1.charAt(2))
console.log(name1.indexOf('t'))

//String operations
// anchor : ƒ anchor()
//at: ƒ at()
//big: ƒ big()
//blink: ƒ blink()
//bold: ƒ bold()
//charAt: ƒ charAt()
//charCodeAt: ƒ charCodeAt()
//codePointAt: ƒ codePointAt()
//concat: ƒ concat()
//constructor: ƒ String()
//endsWith: ƒ endsWith()
//fixed: ƒ fixed()
//fontcolor: ƒ fontcolor()
//fontsize: ƒ fontsize()
//includes: ƒ includes()
//indexOf: ƒ indexOf()
//isWellFormed: ƒ isWellFormed()
//italics: ƒ italics()
//lastIndexOf: ƒ lastIndexOf()
//length: 0
//link: ƒ link()
//localeCompare: ƒ localeCompare()
//match: ƒ match()
//matchAll: ƒ matchAll()
//normalize: ƒ normalize()
//padEnd: ƒ padEnd()
//padStart: ƒ padStart()
//repeat: ƒ repeat()
//replace: ƒ replace()
//replaceAll: ƒ replaceAll()
//search: ƒ search()
//slice: ƒ slice()
//small: ƒ small()
//split: ƒ split()
//startsWith: ƒ startsWith()
//strike: ƒ strike()
//sub: ƒ sub()
//substr: ƒ substr()
//substring: ƒ substring()
//sup: ƒ sup()
//toLocaleLowerCase: ƒ toLocaleLowerCase()
//toLocaleUpperCase: ƒ toLocaleUpperCase()
//toLowerCase: ƒ toLowerCase()
//toString: ƒ toString()
//toUpperCase: ƒ toUpperCase()
//toWellFormed: ƒ toWellFormed()
//trim: ƒ trim()
//trimEnd: ƒ trimEnd()
//trimLeft: ƒ trimStart()
//trimRight: ƒ trimEnd()
//trimStart: ƒ trimStart()
//valueOf: ƒ valueOf()